Implemented Start Game button.
arorakarnika/Cluegonauts pull request #24
Opened 2024-10-12 04:10 UTC by agrove11

- It is initially disabled.
- Once two players have joined, the buttons become enabled.
- When any player clicks the start button, a game log is created.

2024-10-20 12:39 UTC, arorakarnika commented on poetry-installer-error-sct6sh89.log
@agrove11 Could you remove this file?

2024-10-20 12:44 UTC, arorakarnika requested changes
Changes look good! I'd like to remove the poetry-installer-error file that I think was included by mistake. Should be able to merge in once that file is removed!

2024-10-20 12:44 UTC, arorakarnika commented on cluegonauts/clueless/templates/clueless/index.html
> +        if (playerCount >= 2) {
nicely done!

2024-10-21 23:00 UTC, bruszow1 approved these changes

2024-10-22 00:11 UTC, arorakarnika approved these changes

2024-10-22 00:12 UTC, merged